### PR TITLE
change joe wang to jue wang

### PR DESCRIPTION
**Pull request by isgiddy**
Update name

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Sorry, now i am confused as in the GitHub name it is also Joe.

**Comment by isgiddy** [comment]
Joe emailed to request this change. @joewang54 can you review?

**Comment by joewang54** [comment]
> Joe emailed to request this change. @joewang54 can you review?

Yes, Isabelle. Thank you!
Sorry for the confusion.

**Comment by joewang54** [comment]
> Sorry, i am confused as in the GitHub name it is Jue and Joe? @joewang54 which is correct?

Hi Soeren, how are you?
JUE WANG is my full name. And Joewang was used to register email because someone has used juewang on email account.
Again, sorry for the confusion.

**Pull request merged**
