### PR TITLE
change citation style to author year

### PR DESCRIPTION
**Pull request by soerenthomsen**
This PR will change the citation style to author year as already done for the oxygen SOP here: 
https://github.com/OceanGlidersCommunity/Oxygen_SOP/pull/216

@jbusecke I aim to redo what you/we implemented for the oxygen SOP. Kindly ask @callumrollo and you to review as soon as I am done :) so Issy can focus on her thesis defence!

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Ok this is ready for review! The preview looks good to me 🌊

This PR closes #124

**Review by callumrollo — APPROVED** [review]
Nice job Soeren! Looks good to me. Pretty citations, internal and external links work

**Comment by soerenthomsen** [comment]
Thanks Callum! Another big check

**Review by callumrollo — COMMENTED** [review]
Do you want to pin to pybtex-apa-style>=1.3 as you did for the DAC SOP? https://github.com/OceanGlidersCommunity/DepthAverageCurrents_SOP/pull/123/files

**Pull request merged**
