### PR TITLE
Testing embedded video

### PR DESCRIPTION
**Pull request by jbusecke**
Possible solution to #34.

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Checked the preview deployment and looks great. it is also possible to put the video file into the GitHub repo and embed it directly? Or does it have to be uploaded to a video platform like Vimeo or YouTube before?

**Comment by jbusecke** [comment]
I think it only works with streaming services. Adding videos to the gh repo seems like a bad idea, since they will usually be very big.

**Comment by soerenthomsen** [comment]
And is it possible to upload a gif to the repo?

**Comment by jbusecke** [comment]
That should work just as is! Just watch the size.

**Comment by jbusecke** [comment]
Is this still a desired feature? Or can we close this?

**Comment by soerenthomsen** [comment]
I vote for closing it for now. @isgiddy ? 
Might just create problems with releasing v1.0.0 as pdf etc

**Comment by jbusecke** [comment]
I am closing this. Please reopen if you see necessary.

**Pull request closed without merging**
